title: "Ryoto Takeuchi"
theme: minima
plugins: []

collections:
  learning:
    output: true
    permalink: /learning/:path/

markdown: kramdown
kramdown:
  input: GFM

# Use our custom layouts/includes
include:
  - _includes
  - _layouts
